import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ThemeComponent from "@/components/ThemeProvider/ThemeComponent";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" dir="ltr" suppressHydrationWarning={true}>
        <body>
          <ThemeComponent>
            <Header />
            <NavBar />
            {children}
          </ThemeComponent>
        </body>
      </html>
    </ClerkProvider>
  );
}
